import type { DeckAsset } from "../schemas/deck.js";

/**
 * AI 图片生成占位。在 Skill 驱动工作流中，配图由 Agent 直接生成 SVG 文件，
 * 不再运行时调用 OpenAI Image API。如需启用，请安装 openai 包并实现此函数。
 */
export async function generateGptImage2Asset(_asset: DeckAsset, _outputPath: string): Promise<string> {
  throw new Error("AI image generation is disabled. Use SVG assets generated by the Agent instead.");
}
